### ISSUE TITLE
Scooby Doo Hollywood horror?

### ISSUE THREAD

**Issue by Mitchykins** [mattbruv/ccsr#13]
I assume that game uses the same engine, so it shouldn't be too hard to do a similar decompilation and port, right?

**Comment by TheOnlyZac** [comment]
I'm pretty sure they're same, you can even load the map files from SDHH in my CCSR map viewer and they render almost perfectly.

**Comment by mattbruv** [comment]
#14 Scooby Doo Hollywood Horror episodes 1 & 2 have been added!
